---
title: "Tidy Data"
output: github_document
---

```{r}
library(tidyverse)
```

## `pivot_longer`

Import the PULSE data

```{r}
pulse_df = 
  sas7bdat::read.sas7bdat("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
pulse_df
```

Wide format to long format

```{r}

pulse_tidy = 
  pulse_df %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  )

```
rewrite, combine, and extend (to add a mutate)

```{r}
pulse_df = 
  sas7bdat::read.sas7bdat("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  ) %>% 
  relocate(id,visit) %>% 
  mutate(visit = recode(visit, "bl" = "00m")) # bl means baseline

```

## `pivot_wider`

Make up some data!

```{r}
analysis_result = 
  tibble(
    group = c("treatment","treatment","placebo","placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
  )
analysis_result %>% 
  pivot_wider(
    names_from = "time",
    values_from = "mean"
  )
analysis_result
```

## binding rows

using the LorR data

First step: import each table.

```{r}
fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>% 
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>% 
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>% 
  mutate(movie = "return_king")

```

Bind all the rows together

```{r}
lotr_tidy =
  bind_rows(fellowship_ring, two_towers, return_king) %>% 
  janitor::clean_names() %>% 
  relocate(movie) %>% 
  pivot_longer(
    female:male,
    names_to = "gender",
    values_to = "words"
  )

lotr_tidy
```

